name = "event-webapp"
compatibility_date = "2024-09-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "art_event_1"
database_id = "e483980b-c034-448f-a1a3-9b61d392a13f"

[vars]
EVENT_ID = "printmaking-2026"
EVENT_TITLE = "International Contemporary Printmaking 2026"
MASTER_PORTAL_URL = "http://localhost:8788" # In production: https://master-portal.pages.dev
SHARED_SECRET_TOKEN = "sec_demo_event_2026_xyz"
ADMIN_KEY = "admin123"
# Cloudinary settings for browser unsigned direct upload:
CLOUDINARY_CLOUD_NAME = "event-demo-account"
CLOUDINARY_UPLOAD_PRESET = "virtual_exhibition_preset"
